name: kayvo_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.1
  font_awesome_flutter: ^8.5.0
  flutter_slidable: ^0.5.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  popup_menu: ^1.0.5
  libphonenumber: ^1.0.1
  intl_phone_number_input:
    path: ./intl_phone_number_input
  dash_chat:
    path: ./dash_chat
  alphabet_scroll:
    path: ./alphabet_scroll
  language_scroll:
    path: ./language_scroll
  pincode_textfield:
    path: ./pincode_textfield
  faker: ^1.2.0
  language_pickers: ^0.1.3
  flushbar: ^1.9.1
  simple_animations: ^1.3.6
  flare_splash_screen: ^3.0.1
  flare_flutter: ^2.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/welcome.png
    - assets/verify1.png
    - assets/verify2.png
    - assets/camera-outline.svg
    - assets/pen.svg
    - assets/archive.svg
    - assets/plus.svg
    - assets/default_image.png
    - assets/user-plus.svg
    - assets/ellipsis-v.svg
    - assets/paperclip.svg
    - assets/shield-check.svg
    - assets/settings.svg
    - assets/globe-asia.svg
    - assets/user-friends.svg
    - assets/question-circle.svg
    - assets/comment-dots.svg
    - assets/user-circle.svg
    - assets/bell.svg
    - assets/gif.svg
    - assets/default_contact_image.png
    - assets/demoPic.jpg
    - assets/privacy.png
    - assets/minus-circle.svg
    - assets/change_number.png
    - assets/backup_chat.png
    - assets/alerts_not.png
    - assets/banners_not_active.png
    - assets/none_not.png
    - assets/alerts_not.svg
    - assets/banners_not_active.svg
    - assets/none_not.svg
    - assets/kayvo.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: fonts/Helvetica-Light.ttf
          weight: 300
