name: kayvo_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flare_splash_screen: ^3.0.0
  flutter_svg: ^0.17.1
  font_awesome_flutter: ^8.5.0
  intl_phone_number_input: ^0.3.0
  flutter_icons: ^1.0.0+1
  groovin_material_icons: ^1.1.6
  outline_material_icons: ^0.1.1
  material_design_icons_flutter: ^3.4.4895
  flutter_slidable: ^0.5.4
  search_app_bar: ^1.0.2+2
  search_widget: ^1.0.2
  pin_code_text_field: ^1.5.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg
    - assets/welcome.png
    - assets/verify1.png
    - assets/verify2.png
    - assets/camera-outline.svg
    - assets/pen.svg
    - assets/archive.svg
    - assets/plus.svg
    - assets/default_image.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica.ttf
        - asset: fonts/Helvetica-Bold.ttf
          weight: 700
        - asset: fonts/Helvetica-Light.ttf
          weight: 300
