final List defaultLanguagesList = [
  {"isoCode": "	af	", "name": "	Afrikaans	"},
  {"isoCode": "	sq	", "name": "	Albanian	"},
  {"isoCode": "	am	", "name": "	Amharic	"},
  {"isoCode": "	ar	", "name": "	Arabic	"},
  {"isoCode": "	hy	", "name": "	Armenian	"},
  {"isoCode": "	az	", "name": "	Azerbaijani	"},
  {"isoCode": "	eu	", "name": "	Basque	"},
  {"isoCode": "	be	", "name": "	Belarusian	"},
  {"isoCode": "	bn	", "name": "	Bengali	"},
  {"isoCode": "	bs	", "name": "	Bosnian	"},
  {"isoCode": "	bg	", "name": "	Bulgarian	"},
  {"isoCode": "	ca	", "name": "	Catalan	"},
  {"isoCode": "	ceb	", "name": "	Cebuano	"},
  {"isoCode": "	zh	", "name": "	Chinese (Simplified)	"},
  {"isoCode": "	zh-TW	", "name": "	Chinese (Traditional)	"},
  {"isoCode": "	co	", "name": "	Corsican	"},
  {"isoCode": "	hr	", "name": "	Croatian	"},
  {"isoCode": "	cs	", "name": "	Czech	"},
  {"isoCode": "	da	", "name": "	Danish	"},
  {"isoCode": "	nl	", "name": "	Dutch	"},
  {"isoCode": "	en	", "name": "	English	"},
  {"isoCode": "	eo	", "name": "	Esperanto	"},
  {"isoCode": "	et	", "name": "	Estonian	"},
  {"isoCode": "	fi	", "name": "	Finnish	"},
  {"isoCode": "	fr	", "name": "	French	"},
  {"isoCode": "	fy	", "name": "	Frisian	"},
  {"isoCode": "	gl	", "name": "	Galician	"},
  {"isoCode": "	ka	", "name": "	Georgian	"},
  {"isoCode": "	de	", "name": "	German	"},
  {"isoCode": "	el	", "name": "	Greek	"},
  {"isoCode": "	gu	", "name": "	Gujarati	"},
  {"isoCode": "	ht	", "name": "	Haitian Creole	"},
  {"isoCode": "	ha	", "name": "	Hausa	"},
  {"isoCode": "	haw	", "name": "	Hawaiian	"},
  {"isoCode": "	he or iw	", "name": "	Hebrew	"},
  {"isoCode": "	hi	", "name": "	Hindi	"},
  {"isoCode": "	hmn	", "name": "	Hmong	"},
  {"isoCode": "	hu	", "name": "	Hungarian	"},
  {"isoCode": "	is	", "name": "	Icelandic	"},
  {"isoCode": "	ig	", "name": "	Igbo	"},
  {"isoCode": "	id	", "name": "	Indonesian	"},
  {"isoCode": "	ga	", "name": "	Irish	"},
  {"isoCode": "	it	", "name": "	Italian	"},
  {"isoCode": "	ja	", "name": "	Japanese	"},
  {"isoCode": "	jv	", "name": "	Javanese	"},
  {"isoCode": "	kn	", "name": "	Kannada	"},
  {"isoCode": "	kk	", "name": "	Kazakh	"},
  {"isoCode": "	km	", "name": "	Khmer	"},
  {"isoCode": "	ko	", "name": "	Korean	"},
  {"isoCode": "	ku	", "name": "	Kurdish	"},
  {"isoCode": "	ky	", "name": "	Kyrgyz	"},
  {"isoCode": "	lo	", "name": "	Lao	"},
  {"isoCode": "	la	", "name": "	Latin	"},
  {"isoCode": "	lv	", "name": "	Latvian	"},
  {"isoCode": "	lt	", "name": "	Lithuanian	"},
  {"isoCode": "	lb	", "name": "	Luxembourgish	"},
  {"isoCode": "	mk	", "name": "	Macedonian	"},
  {"isoCode": "	mg	", "name": "	Malagasy	"},
  {"isoCode": "	ms	", "name": "	Malay	"},
  {"isoCode": "	ml	", "name": "	Malayalam	"},
  {"isoCode": "	mt	", "name": "	Maltese	"},
  {"isoCode": "	mi	", "name": "	Maori	"},
  {"isoCode": "	mr	", "name": "	Marathi	"},
  {"isoCode": "	mn	", "name": "	Mongolian	"},
  {"isoCode": "	my	", "name": "	Myanmar (Burmese)	"},
  {"isoCode": "	ne	", "name": "	Nepali	"},
  {"isoCode": "	no	", "name": "	Norwegian	"},
  {"isoCode": "	ny	", "name": "	Nyanja (Chichewa)	"},
  {"isoCode": "	ps	", "name": "	Pashto	"},
  {"isoCode": "	fa	", "name": "	Persian	"},
  {"isoCode": "	pl	", "name": "	Polish	"},
  {"isoCode": "	pt	", "name": "	Portuguese (Portugal, Brazil)	"},
  {"isoCode": "	pa	", "name": "	Punjabi	"},
  {"isoCode": "	ro	", "name": "	Romanian	"},
  {"isoCode": "	ru	", "name": "	Russian	"},
  {"isoCode": "	sm	", "name": "	Samoan	"},
  {"isoCode": "	gd	", "name": "	Scots Gaelic	"},
  {"isoCode": "	sr	", "name": "	Serbian	"},
  {"isoCode": "	st	", "name": "	Sesotho	"},
  {"isoCode": "	sn	", "name": "	Shona	"},
  {"isoCode": "	sd	", "name": "	Sindhi	"},
  {"isoCode": "	si	", "name": "	Sinhala (Sinhalese)	"},
  {"isoCode": "	sk	", "name": "	Slovak	"},
  {"isoCode": "	sl	", "name": "	Slovenian	"},
  {"isoCode": "	so	", "name": "	Somali	"},
  {"isoCode": "	es	", "name": "	Spanish	"},
  {"isoCode": "	su	", "name": "	Sundanese	"},
  {"isoCode": "	sw	", "name": "	Swahili	"},
  {"isoCode": "	sv	", "name": "	Swedish	"},
  {"isoCode": "	tl	", "name": "	Tagalog (Filipino)	"},
  {"isoCode": "	tg	", "name": "	Tajik	"},
  {"isoCode": "	ta	", "name": "	Tamil	"},
  {"isoCode": "	te	", "name": "	Telugu	"},
  {"isoCode": "	th	", "name": "	Thai	"},
  {"isoCode": "	tr	", "name": "	Turkish	"},
  {"isoCode": "	uk	", "name": "	Ukrainian	"},
  {"isoCode": "	ur	", "name": "	Urdu	"},
  {"isoCode": "	uz	", "name": "	Uzbek	"},
  {"isoCode": "	vi	", "name": "	Vietnamese	"},
  {"isoCode": "	cy	", "name": "	Welsh	"},
  {"isoCode": "	xh	", "name": "	Xhosa	"},
  {"isoCode": "	yi	", "name": "	Yiddish	"},
  {"isoCode": "	yo	", "name": "	Yoruba	"},
  {"isoCode": "	zu	", "name": "	Zulu	"},
];
